export const data = [
    {
        id: 're-1',
        keyword: '尴尬',
        sentence: 'Usual Frame: I am bored with life. Reframe: I am not embarrassing myself enough.',
        chinese: '常规框架：我对生活感到无聊。重构框架：我还不够让自己尴尬。',
    },
    {
        id: 're-2',
        keyword: '尴尬',
        sentence: 'Usual Frame: Embarrassment is something to be avoided. Reframe: Embarrassment is an investment.',
        chinese: '常规框架：尴尬是要避免的。重构框架：尴尬是一项投资。',
    },
    {
        id: 're-3',
        keyword: '成功',
        sentence: 'Usual Frame: Success requires setting goals. Reframe: Systems are better than goals.',
        chinese: '常规框架：成功需要设定目标。重构框架：系统比目标更重要。',
    },
    {
        id: 're-4',
        keyword: '度量',
        sentence: 'Usual Frame: Measure twice, cut once. Reframe: Just start. See if you can figure it out as you go.',
        chinese: '常规框架：量两次，切一次。重构框架：开始吧，看你是否能在过程中搞明白。',
    },
    {
        id: 're-5',
        keyword: '不幸运',
        sentence: 'Usual Frame: I am unusually unlucky this happened to me. Reframe: Everyone has problems. No exceptions.',
        chinese: '常规框架：我很不幸运，发生了这样的事。重构框架：每个人都有问题，没有例外。',
    },
    {
        id: 're-6',
        keyword: '好主意',
        sentence: 'Usual Frame: I need to come up with a good idea. Reframe: I need to release all my bad ideas as quickly as possible.',
        chinese: '常规框架：我需要想出一个好主意。重构框架：我需要尽快释放掉所有坏主意。',
    },
    {
        id: 're-7',
        keyword: '冒充者',
        sentence: 'Usual Frame: I feel like an impostor at my job. Reframe: Everyone is an impostor.',
        chinese: '常规框架：我感觉自己在工作中像个冒充者。重构框架：每个人都是冒充者。',
    },
    {
        id: 're-8',
        keyword: '情绪',
        sentence: 'Usual Frame: Your mood is determined by your internal thoughts. Reframe: You can improve your mood by completing meaningful tasks.',
        chinese: '常规框架：你的情绪由你内心的想法决定。重构框架：你可以通过完成有意义的任务来改善情绪。',
    },
    {
        id: 're-9',
        keyword: '社交媒体',
        sentence: 'Usual Frame: Social media is a form of entertainment. Reframe: Social media is an addiction.',
        chinese: '常规框架：社交媒体是一种娱乐形式。重构框架：社交媒体是一种上瘾。',
    },
    {
        id: 're-10',
        keyword: '侮辱',
        sentence: 'Usual Frame: An insult is damaging to my mental health. Reframe: An insult is a confession that your accuser can\'t refute your opinion and/or has personal problems of some sort.',
        chinese: '常规框架：侮辱会损害我的心理健康。重构框架：侮辱是对方无法反驳你的观点和/或有某种个人问题的自白。',
    },
    {
        id: 're-11',
        keyword: '自我',
        sentence: 'Usual Frame: Your ego is "you," and it must be protected. Reframe: Your ego is your enemy.',
        chinese: '常规框架：你的自我就是“你”，它必须被保护。重构框架：你的自我就是你的敌人。',
    },
    {
        id: 're-12',
        keyword: '尴尬',
        sentence: 'Usual Frame: Avoid embarrassment. Reframe: Invite embarrassment and use it as a club to kill your ego.',
        chinese: '常规框架：避免尴尬。重构框架：迎接尴尬，并将其用作击败自我的武器。',
    },
    {
        id: 're-13',
        keyword: '压力',
        sentence: 'Usual Frame: My stress and anxiety are caused by events in my life. Reframe: I won\'t care about any of those events on my deathbed.',
        chinese: '常规框架：我的压力和焦虑是由生活中的事件引起的。重构框架：在临终时我不会在乎那些事件。',
    },
    {
        id: 're-14',
        keyword: '消极思想',
        sentence: 'Usual Frame: You need to stop thinking negative thoughts. Reframe: You can\'t subtract negative thoughts. But you can crowd them out.',
        chinese: '常规框架：你需要停止消极的思维。重构框架：你不能消除消极思想，但可以将其挤出。',
    },
    {
        id: 're-15',
        keyword: '他人评价',
        sentence: 'Usual Frame: People judge me, so I feel bad when I mess up. Reframe: People only care about themselves. They don\'t care what dumb thing I did recently, even if they mention it.',
        chinese: '常规框架：人们评判我，所以我犯错时会感到难过。重构框架：人们只关心自己。他们根本不在乎我最近犯的傻事，即使提到也无所谓。',
    },
    {
        id: 're-16',
        keyword: '成瘾',
        sentence: 'Usual Frame: Avoid addiction. Reframe: Choose your addictions wisely.',
        chinese: '常规框架：避免成瘾。重构框架：明智地选择你的成瘾。',
    },
    {
        id: 're-17',
        keyword: '日子',
        sentence: 'Usual Frame: There are good days and bad. Reframe: All days are useful in different ways.',
        chinese: '常规框架：有好日子也有坏日子。重构框架：每一天都有不同的用途。',
    },
    {
        id: 're-18',
        keyword: '过去的创伤',
        sentence: 'Usual Frame: I am a victim of my past traumas. Reframe: History is imaginary.',
        chinese: '常规框架：我是过去创伤的受害者。重构框架：历史是虚构的。',
    },
    {
        id: 're-19',
        keyword: '创伤',
        sentence: 'Usual Frame: You are the result of your traumas. Reframe: You are a random bundle of loose wires.',
        chinese: '常规框架：你是创伤的结果。重构框架：你是一个随机的松散电线捆。',
    },
    {
        id: 're-20',
        keyword: '创伤的影响',
        sentence: 'Usual Frame: My trauma crippled me. Reframe: My trauma is why I can kick your ass.',
        chinese: '常规框架：我的创伤使我瘫痪。重构框架：我的创伤使我能够踢你的屁股。',
    },
    {
        id: 're-21',
        keyword: '活在当下',
        sentence: 'Usual Frame: Live in the now. Reframe: Imagine even your smallest actions influencing your future.',
        chinese: '常规框架：活在当下。重构框架：想象即使是你最微小的行为，也能影响你的未来。',
    },
    {
        id: 're-22',
        keyword: '幸福',
        sentence: 'Usual Frame: Happiness comes from within. Reframe: Use the external world to program your brain for happiness.',
        chinese: '常规框架：幸福源自内心。重构框架：利用外部世界为你的大脑编程，获得幸福。',
    },
    {
        id: 're-23',
        keyword: '善行',
        sentence: 'Usual Frame: Small acts of kindness are good. Reframe: There are no small acts of kindness.',
        chinese: '常规框架：小小的善行是好的。重构框架：没有小的善行。',
    },
    {
        id: 're-24',
        keyword: '饥饿',
        sentence: 'Usual Frame: When I am hungry, I eat food. Reframe: Some food is fuel. Some food is entertainment.',
        chinese: '常规框架：当我饿的时候，我吃东西。重构框架：一些食物是燃料，一些食物是娱乐。',
    },
    {
        id: 're-25',
        keyword: '暴饮暴食',
        sentence: 'Usual Frame: Overeating is a willpower problem. Reframe: Overeating is a knowledge problem.',
        chinese: '常规框架：暴饮暴食是意志力的问题。重构框架：暴饮暴食是知识的问题。',
    },
    {
        id: 're-26',
        keyword: '饥饿与食欲',
        sentence: 'Usual Frame: I want food, so I must be hungry. Reframe: I want food, so I might be tired.',
        chinese: '常规框架：我想吃东西，所以我一定饿了。重构框架：我想吃东西，所以我可能累了。',
    },
    {
        id: 're-27',
        keyword: '减肥目标',
        sentence: 'Usual Frame: I have a weight loss goal. Reframe: I need to create a weight loss system for myself.',
        chinese: '常规框架：我有一个减肥目标。重构框架：我需要为自己创造一个减肥系统。',
    },
    {
        id: 're-28',
        keyword: '饥饿',
        sentence: 'Usual Frame: I\'m hungry, so I need food. Reframe: I\'m hungry, so I need protein.',
        chinese: '常规框架：我饿了，所以我需要食物。重构框架：我饿了，所以我需要蛋白质。',
    },
]
