CREATE TABLE IF NOT EXISTS all_reframe_js (
  id text PRIMARY KEY,
  chapter text NOT NULL,
  keyword text NOT NULL,
  sentence text NOT NULL,
  chinese text NOT NULL,
  idx integer NOT NULL,
  favorite_local boolean NOT NULL DEFAULT false
);

INSERT INTO all_reframe_js (id, chapter, keyword, sentence, chinese, idx, favorite_local) VALUES
('Test-1','Test','测试','Usual Frame: Taking the dog, for a walk and failing.','常规框架：遛狗没做好',0,true),
('Test-2','Test','测试2','Usual Frame: for.','常规框架：遛狗没做好',500,true),
('Test-3','Test','测试3','Usual Frame: for a walk and failing.','常规框架：遛狗没做好',501,true),
('Test-4','Test','测试4','Usual Frame Test4.','常规框架4',502,true),
('Test-5','Test','测试5','Usual Frame Test5.','常规框架5',503,true),
('intro-1','Introduction Reframes','遛狗','Usual Frame: Taking the dog for a walk and failing. Reframe: Taking the dog for a sniff and succeeding.','常规框架：遛狗没做好。重构框架：让狗狗尽情嗅闻就是成功。',1,true),
('intro-2','Introduction Reframes','无所事事','Usual Frame: I have nothing to do. I am just standing here. Reframe: Perfect time to practice proper breathing and posture.','常规框架：我无事可做，只是站着。重构框架：正好练习呼吸和姿势。',2,true),
('intro-3','Introduction Reframes','排队','Usual Frame: I am waiting in line, which is a waste of time. Reframe: I have time to breathe properly.','常规框架：排队是在浪费时间。重构框架：我有时间好好呼吸。',3,true),
('intro-4','Introduction Reframes','饮酒','Usual Frame: Alcohol is a beverage. Reframe: Alcohol is poison.','常规框架：酒是饮料。重构框架：酒是毒药。',4,true),
('success-1','Success Reframes','成功概率','Usual Frame: My odds of success are low. Reframe: Maybe I am bad at estimating the odds.','常规框架：我的成功概率很低。重构框架：也许我只是对成功概率的估计不准确。',5,true),
('success-2','Success Reframes','失败比例','Usual Frame: I fail at 90 percent of the things I try. Reframe: I only need to succeed 10 percent of the time.','常规框架：我尝试的事情有90%都失败。重构框架：我只需要有10%的成功就够了。',6,true),
('success-3','Success Reframes','决心','Usual Frame: I want to do (something). Reframe: I have decided to do (something).','常规框架：我想做某事。重构框架：我已经决定去做某事。',7,true),
('success-4','Success Reframes','管理目标','Usual Frame: Manage your time. Reframe: Manage your energy.','常规框架：管理你的时间。重构框架：管理你的精力。',8,true),
('success-5','Success Reframes','工作目标','Usual Frame: Your job is what your boss tells you it is. Reframe: Your job is to get a better job.','常规框架：你的工作就是老板分配的。重构框架：你的工作是让自己找到更好的工作。',9,true),
('success-6','Success Reframes','无聊','Usual Frame: I am bored with life. Reframe: I am not embarrassing myself enough.','常规框架：我对生活感到无聊。重构框架：我还不够让自己感到尴尬。',10,true),
('success-7','Success Reframes','尴尬','Usual Frame: Embarrassment is something to be avoided. Reframe: Embarrassment is an investment.','常规框架：尴尬要避免。重构框架：尴尬是一种投资。',11,true),
('success-8','Success Reframes','犯错','Usual Frame: Being wrong is embarrassing and should be avoided. Reframe: Fear of embarrassment forces you to be wrong.','常规框架：犯错是尴尬的，并且要避免。重构框架：害怕尴尬会让你错得更多。',12,true),
('success-9','Success Reframes','行动','Usual Frame: The effort is so big and daunting I can''t even start. Reframe: What''s the smallest thing I can do that moves me in the right direction?','常规框架：努力太大太难以开始。重构框架：我能做的最小的一步是什么？',13,true),
('success-10','Success Reframes','目标与系统','Usual Frame: Success requires setting goals. Reframe: Systems are better than goals.','常规框架：成功需要设目标。重构框架：用系统比设定目标更有效。',14,true),
('success-11','Success Reframes','技能组合','Usual Frame: Focus on being excellent at a skill that has commercial value. Reframe: Acquire skills that work well together and make you rare and flexible at the same time.','常规框架：专注于一项有商业价值的技能。重构框架：让不同技能组合，使你更独特灵活。',15,true),
('success-12','Success Reframes','问题与挑战','Usual Frame: Another problem! Why me??? Reframe: Ooh, a new puzzle to solve.','常规框架：又遇到问题了，为什么是我？重构框架：新难题，太好了可以挑战一下。',16,true),
('success-13','Success Reframes','重复事务','Usual Frame: Ugh, I hate this repetitive chore. Reframe: I can do this chore so gracefully and efficiently it feels like a game.','常规框架：我讨厌做这些重复的杂务。重构框架：我可以把它变成类似游戏的练习。',17,true),
('success-14','Success Reframes','激情','Usual Frame: Passion is the key to success. Reframe: Passion is nice but not required.','常规框架：激情是成功的关键。重构框架：激情很好但不是必须的。',18,true),
('success-15','Success Reframes','赚钱','Usual Frame: It takes money to make money. Reframe: I can turn energy into money.','常规框架：用钱赚钱。重构框架：可以把精力变成钱。',19,true),
('success-16','Success Reframes','付出与回报','Usual Frame: Don''t give something for nothing. Reframe: Giving triggers reciprocity (on average).','常规框架：不给予就不会得到。重构框架：给予会激发回报（平均而言）。',20,true),
('success-17','Success Reframes','工作态度','Usual Frame: Do your job. Reframe: Do more than your job.','常规框架：把自己的工作做好。重构框架：多做一些超出本职工作。',21,true),
('success-18','Success Reframes','人脉关系','Usual Frame: Success depends on who you know. Reframe: Success depends on how many people you know.','常规框架：成功取决于你认识谁。重构框架：取决于你认识多少人。',22,true),
('success-19','Success Reframes','努力成果','Usual Frame: Your hard work will be rewarded. Reframe: The illusion of hard work will be rewarded.','常规框架：努力会有回报。重构框架：努力的"假象"更易被奖励。',23,true),
('success-20','Success Reframes','主动性','Usual Frame: Do what you are told. Reframe: Do what you are NOT told but maybe someone should have.','常规框架：做被要求做的事。重构框架：做没人要求但应该有人做的事。',24,true),
('success-21','Success Reframes','学习方式','Usual Frame: Learn what you need. Reframe: Learn continuously, especially skills that work well together.','常规框架：学自己需要的。重构框架：持续学习，尤其学互补技能。',25,true),
('success-22','Success Reframes','执行计划','Usual Frame: A plan will either work or not. Reframe: Friction and incentives always work. We just don''t know how well until they are tested.','常规框架：计划要么行要么不行。重构框架：摩擦力和激励机制总是有效的，只是程度不同，要测试才知道。',26,true),
('success-23','Success Reframes','行动策略','Usual Frame: Measure twice, cut once. Reframe: Just start. See if you can figure it out as you go.','常规框架：三思后行。重构框架：先开始，边做边调整。',27,true),
('success-24','Success Reframes','学习心态','Usual Frame: School is boring but necessary. Reframe: School is a competitive event. Game on.','常规框架：学校无聊但必要。重构框架：学校像竞技场，开玩吧！',28,true),
('success-25','Success Reframes','竞争','Usual Frame: Compete against yourself and try to improve over time. Reframe: Compete against others even if the others are unaware of the competition.','常规框架：和自己比，慢慢进步。重构框架：和别人比，无论别人知不知道。',29,true),
('success-26','Success Reframes','批评反馈','Usual frame: You did this wrong. Reframe: Your other work is stronger.','常规框架：你做错了。重构框架：你的其他作品更棒。',30,true),
('success-27','Success Reframes','批评方式','Usual Frame: Tell people what they did wrong, so they avoid it next time. Reframe: Tell people what they did well so they are motivated to continue improving.','常规框架：告诉别人做错了什么。重构框架：表扬做得好的地方激励进步。',31,true),
('success-28','Success Reframes','归因认知','Usual Frame: The universe is acting against me. Reframe: The universe owes me.','常规框架：宇宙与我为敌。重构框架：宇宙欠我。',32,true),
('success-29','Success Reframes','运气','Usual Frame: Luck is random and can''t be managed. Reframe: You can go where there is more luck (more energy).','常规框架：运气无规律。重构框架：你可以去到更有机会的地方。',33,true),
('success-30','Success Reframes','不幸感','Usual Frame: I am unusually unlucky this happened to me. Reframe: Everyone has problems. No exceptions.','常规框架：倒霉的事悄然发生在我身上。重构框架：每个人都有问题。',34,true),
('success-31','Success Reframes','公平','Usual Frame: Things should be fair. (me) Reframe: Life isn''t fair. (Mom)','常规框架：事情应该公平。重构框架：人生本就不公平。',35,true),
('success-32','Success Reframes','社会公平','Usual Frame: Fairness is a desirable social goal. Reframe: Fairness is the enemy of success.','常规框架：公平是值得追求的目标。重构框架：公平其实会阻碍成功。',36,true),
('success-33','Success Reframes','创作失误','Usual Frame: Avoid mistakes in your art. Reframe: Invite mistakes into your art and keep the "good ones."','常规框架：艺术创作要避免错误。重构框架：拥抱失误，保留其中的"好错"。',37,true),
('success-34','Success Reframes','灵感','Usual Frame: I need to come up with a good idea. Reframe: I need to release all my bad ideas as quickly as possible.','常规框架：我要有个好点子。重构框架：先把所有坏点子都掏出来。',38,true),
('success-35','Success Reframes','冒充者综合症','Usual Frame: You feel like a fraud. Everyone else is competent. Reframe: You are learning fast. Look at all you learned!','常规框架：你觉得自己是冒充者，别人都很能干。重构框架：你学得很快，看看你都学会了什么！',39,true),
('success-36','Success Reframes','职场冒充','Usual Frame: I feel like an impostor at my job. Reframe: Everyone is an impostor.','常规框架：我觉得自己是冒牌员工。重构框架：大家都是冒充者。',40,true),
('success-37','Success Reframes','情绪调节','Usual Frame: Your mood is determined by your internal thoughts. Reframe: You can improve your mood by completing meaningful tasks.','常规框架：心情由内在想法决定。重构框架：完成有意义的事情会让你心情变好。',41,true),
('success-38','Success Reframes','管理定义','Usual Frame: Whatever managers do is managing. Reframe: If you are not measuring, you are not managing.','常规框架：经理在做的事情就是管理。重构框架：没有度量就没有管理。',42,true),
('success-39','Success Reframes','艺术评价','Usual Frame: Some art is good, and some is bad. Reframe: If there is a market for the art, it is good art.','常规框架：有的艺术好，有的艺术糟。重构框架：有市场的艺术就是好艺术。',43,true),
('success-40','Success Reframes','作品热度','Usual Frame: Praise for your creation predicts you have a hit. Reframe: Only action predicts a hit, not words. Watch for people to extend or modify your creation.','常规框架：别人夸你的作品说明它能火。重构框架：真正火的是别人会主动延伸或模仿的。',44,true),
('success-41','Success Reframes','写作环境','Usual Frame: I can''t think of anything to write. Reframe 1: I''m in the wrong environment for writing.','常规框架：我写不出东西。重构框架：我写作环境不对。',45,true),
('success-42','Success Reframes','写作时机','Usual Frame: I have writer''s block. Reframe 2: I''m trying to write at the wrong time of day.','常规框架：我写不出来有写作障碍。重构框架：写作时机选错了。',46,true),
('success-43','Success Reframes','写作要求','Usual Frame: I can''t think of anything good to write. Reframe 3: I can write something bad and fix it.','常规框架：写不出好东西。重构框架：先写出烂的再修。',47,true),
('mental-1','Mental Health Reframes','内心想法','Usual Frame: I am my inner thoughts. Reframe: I am what I do.','常规框架：我是我的内心想法。重构框架：我是我的行为。',48,true),
('mental-2','Mental Health Reframes','认识自我','Usual Frame: Find yourself. Reframe: Author yourself.','常规框架：寻找自我。重构框架：创造自我。',49,true),
('mental-3','Mental Health Reframes','好人与坏人','Usual Frame: Some people are good, and some are not. Reframe: We''re all flawed, and we''re all good at different things.','常规框架：有的人是好人，有的人不是。重构框架：我们都有缺点，也都各有所长。',50,true),
('mental-4','Mental Health Reframes','艺术定义','Usual Frame: Art is entertainment. Reframe: Art is a powerful, mind-altering drug.','常规框架：艺术是娱乐。重构框架：艺术是改变心智的强大药物。',51,true),
('mental-5','Mental Health Reframes','对待批评者','Usual Frame: Your critics are evil monsters. Reframe: Your critics are your mascots.','常规框架：批评你的人是恶魔。重构框架：批评你的人是你的吉祥物。',52,true),
('mental-6','Mental Health Reframes','批评感受','Usual Frame: Criticism feels like a dagger to your heart. Reframe: Criticism is a chemical reaction in the skull of someone who isn''t in the room.','常规框架：批评像匕首刺向你的心脏。重构框架：批评只是没在你面前的人头脑中的化学反应。',53,true),
('mental-7','Mental Health Reframes','他人建议','Usual Frame: You should do what I think you should do. Reframe: Go eat fudge. (Spoken only in your mind.)','常规框架：你应该按照我说的做。重构框架：去吃巧克力吧（只在你心里想）。',54,true),
('mental-8','Mental Health Reframes','自我中心','Usual Frame: Everyone is thinking about me. Reframe: You are only a bit player in their movie.','常规框架：每个人都在想我。重构框架：你只是他人电影里的配角。',55,true),
('mental-9','Mental Health Reframes','社交媒体','Usual Frame: Social media is a form of entertainment. Reframe: Social media is an addiction.','常规框架：社交媒体是一种娱乐。重构框架：社交媒体是一种上瘾。',56,true),
('mental-10','Mental Health Reframes','侮辱','Usual Frame: An insult is damaging to my mental health. Reframe: An insult is a confession that your accuser can''t refute your opinion and/or has personal problems of some sort.','常规框架：侮辱会损伤我的心理健康。重构框架：侮辱其实是对方不能反驳你的观点或有自身问题的自白。',57,true),
('mental-11','Mental Health Reframes','被讨厌','Usual Frame: An insult hurts because it means someone dislikes or disrespects you. Reframe: A stranger''s opinion of you - even if it gets published in The New York Times - is little more than their personal diary entry.','常规框架：侮辱很伤人，因为有人讨厌或不尊重你。重构框架：陌生人对你的看法，即使发表在纽约时报，也不过是人家的日记。',58,true),
('mental-12','Mental Health Reframes','细菌','Usual Frame: Germs will harm me. Reframe: Germs make me stronger.','常规框架：细菌会伤害我。重构框架：细菌让我更强壮。',59,true),
('mental-13','Mental Health Reframes','寒冷','Usual Frame: Coldness is pain and a signal I am in danger. Reframe: Coldness makes me healthier and stronger.','常规框架：寒冷意味着痛苦和危险。重构框架：寒冷让我更健康、强壮。',60,true),
('mental-14','Mental Health Reframes','死亡的意义','Usual Frame: Death is a tragedy, and I need to feel bad about it. Reframe: The deceased has no more problems. How did I make this about me?','常规框架：死亡是悲剧，我得难过。重构框架：去世的人再无烦恼，怎么变成了我的痛苦？',61,true),
('mental-15','Mental Health Reframes','死亡的看法','Usual Frame: Death is a tragedy. Reframe: It is an honor to help another pass.','常规框架：死亡是悲剧。重构框架：能陪伴他人走完人生是一种荣誉。',62,true),
('mental-16','Mental Health Reframes','情感与处境','Usual Frame: My feelings are the result of my situation. Reframe: How I feel is my choice.','常规框架：我的感受是境遇造成的。重构框架：我的感受由我选择。',63,true),
('mental-17','Mental Health Reframes','仇恨','Usual Frame: I hate someone who deserves it. Reframe: Hate is nothing but punishing myself for the misdeeds of others.','常规框架：我恨罪有应得的人。重构框架：仇恨只是用来惩罚自己的工具。',64,true),
('mental-18','Mental Health Reframes','怨恨和愤怒','Usual Frame: Hate and anger are toxic feelings you hope will wear off. Reframe: Hate and anger are a superpower level of energy you can use for gain.','常规框架：愤恨和愤怒是有毒的，希望它能自消。重构框架：仇恨和愤怒是一种可被利用的重要能量。',65,true),
('mental-19','Mental Health Reframes','问题存在','Usual Frame: Why can''t my problems go away? Reframe: Everything has a right to exist, including this problem.','常规框架：为什么我的问题不能消失？重构框架：每个问题都有存在的权利。',66,true),
('mental-20','Mental Health Reframes','自我（ego）','Usual Frame: Your ego is ''you,'' and it must be protected. Reframe: Your ego is your enemy.','常规框架：自我是你本人，必须被保护。重构框架：自我是你的敌人。',67,true),
('mental-21','Mental Health Reframes','避免尴尬','Usual Frame: Avoid embarrassment. Reframe: Invite embarrassment and use it as a club to kill your ego.','常规框架：要避免尴尬。重构框架：主动迎接尴尬，用它斩杀你的自我。',68,true),
('mental-22','Mental Health Reframes','自我形象','Usual Frame: I am a priceless work of art that must be protected. Reframe: I am a potato that is easily replaced.','常规框架：我是无价之宝，需被保护。重构框架：我就是一颗土豆，随时能被替换。',69,true),
('mental-23','Mental Health Reframes','担忧未来','Usual Frame: I worry something will go wrong. Reframe: I''m curious what will happen.','常规框架：我担心出事。重构框架：我好奇会发生什么。',70,true),
('mental-24','Mental Health Reframes','应对消极','Usual Frame: Worry about all potential bad outcomes. Reframe: Control the heck out of things you can control. Accept all outcomes.','常规框架：担忧所有坏结果。重构框架：控制你能控制的，接受所有结果。',71,true),
('mental-25','Mental Health Reframes','历史重要性','Usual Frame: History is important. Reframe: History doesn''t exist.','常规框架：历史很重要。重构框架：历史不存在。',72,true),
('mental-26','Mental Health Reframes','现实观','Usual Frame: Reality is exactly what you see and feel. Reframe: Imagine the objects around you as virtual objects.','常规框架：现实就是所见所感。重构框架：把周围看作虚拟的。',73,true),
('mental-27','Mental Health Reframes','压力和焦虑','Usual Frame: My stress and anxiety are caused by events in my life. Reframe: I won''t care about any of those events on my deathbed.','常规框架：我的压力和焦虑是生活导致的。重构框架：死前你不会关心这些事。',74,true),
('mental-28','Mental Health Reframes','疼痛','Usual Frame: I am in pain. Reframe: I am in pain for a minute.','常规框架：我很痛苦。重构框架：痛苦只持续一分钟。',75,true),
('mental-29','Mental Health Reframes','自我至上','Usual Frame: You are the center of your universe and the highest priority. Reframe: Viewed from space, everything looks small, including your problems.','常规框架：你是自己宇宙的中心，是最重要的。重构框架：站在太空看，一切包括你的烦恼都很渺小。',76,true),
('mental-30','Mental Health Reframes','消极念头','Usual Frame: You need to stop thinking negative thoughts. Reframe: You can''t subtract negative thoughts. But you can crowd them out.','常规框架：你要停止消极思考。重构框架：你无法消除负面念头，但可以用别的想法挤掉它们。',77,true),
('mental-31','Mental Health Reframes','害怕行动','Usual Frame: I''m afraid to do the thing I know I should do. Reframe: Life is short.','常规框架：我害怕做该做的事。重构框架：人生苦短。',78,true),
('mental-32','Mental Health Reframes','强迫性行为','Usual Frame: I must do this pattern of behavior or else something bad will happen. Reframe: I no longer need to do the behavior because less is more.','常规框架：我必须做这件事，否则会有坏事发生。重构框架：我不再需要这样，少即是多。',79,true),
('mental-33','Mental Health Reframes','自信','Usual Frame: Confidence is something you''re born with. Reframe: Confidence is something you learn.','常规框架：自信是天生的。重构框架：自信是可以习得的。',80,true),
('mental-34','Mental Health Reframes','社交能力','Usual Frame: People have better social skills than I do. Reframe: I am in the top 10 percent of people with good social skills (after reading this chapter).','常规框架：别人社交能力比我好。重构框架：看完本章我已是社交前10%。',81,true),
('mental-35','Mental Health Reframes','社交场合','Usual Frame: Each person at the gathering is a source of potential embarrassment for me. Reframe: Each person has a problem (social awkwardness) that I can solve right now.','常规框架：聚会里每个人都可能让我尴尬。重构框架：每个人都有社交尴尬，我可以帮他们。',82,true),
('mental-36','Mental Health Reframes','无聊','Usual Frame: No one wants to talk to me. I''m boring. Reframe: Everyone enjoys talking to people who show interest in them.','常规框架：没人愿理我，我很无聊。重构框架：每个人都喜欢有人对自己感兴趣。',83,true),
('mental-37','Mental Health Reframes','做自己','Usual Frame: Be yourself and keep it real. Reframe: Adjust your communication style for the situation.','常规框架：做自己，坦诚待人。重构框架：针对情境调整表达风格。',84,true),
('mental-38','Mental Health Reframes','选对决策','Usual Frame: Is this a good decision? Reframe: Can we test it small?','常规框架：这是一个好决定吗？重构框架：我们能否小范围试试？',85,true),
('mental-39','Mental Health Reframes','被评价','Usual Frame: People judge me, so I feel bad when I mess up. Reframe: People only care about themselves. They don''t care what dumb thing I did recently, even if they mention it.','常规框架：别人评价我，导致我犯错会难过。重构框架：别人只关心自己，不真的在意你的糗事。',86,true),
('mental-40','Mental Health Reframes','压力归因','Usual Frame: Stress comes with the job. Reframe: Reducing stress IS your job.','常规框架：工作自带压力。重构框架：你的工作是降低压力。',87,true),
('mental-41','Mental Health Reframes','幸存者困扰','Usual Frame: Why did I survive when others did not? Reframe: It''s no different from a clock reading 2:00 PM exactly once a day. It is just cause and effect. It has no meaning.','常规框架：为什么只有我幸存？重构框架：这像时钟每天都会指向2点，只是因果，无特别意义。',88,true),
('mental-42','Mental Health Reframes','幸存者困惑2','Usual Frame: Why did I survive when others did not? Reframe: Every specific thing that has happened to me since birth is extraordinarily unlikely. This is more of that.','常规框架：为什么别人没活下来而我活了？重构框架：我经历的所有事都很不寻常，这也是如此。',89,true),
('mental-43','Mental Health Reframes','为什么是我','Usual Frame: Why me? Reframe: God needs you here for something important.','常规框架：为什么是我？重构框架：上帝需要你留在人间完成重要的事。',90,true),
('mental-44','Mental Health Reframes','内疚','Usual Frame: I feel a responsibility to hold this guilt. Reframe: You have my permission to release your guilt.','常规框架：我有责任背负内疚。重构框架：你可以放下这种内疚。',91,true),
('mental-45','Mental Health Reframes','幸存者愧疚','Usual Frame: I feel bad that I was the lone survivor. Reframe: What would the dead want you to do - suffer or be happy?','常规框架：我是唯一幸存的感觉很内疚。重构框架：死人希望你痛苦还是幸福？',92,true),
('mental-46','Mental Health Reframes','自责','Usual Frame: You could have done more. Reframe: Everyone can do more. It is a meaningless concept.','常规框架：你本可以做得更多。重构框架：每个人都能做更多，这种说法没有意义。',93,true),
('mental-47','Mental Health Reframes','上瘾','Usual Frame: Avoid addiction. Reframe: Choose your addictions wisely.','常规框架：要避免上瘾。重构框架：明智地选择自己的嗜好。',94,true),
('mental-48','Mental Health Reframes','快感和意志力','Usual Frame: People with bad judgment often pursue dangerous and unproductive pleasures. Reframe: People need a minimum level of pleasure to make life worth living, and if they can''t get it safely, they will get it unsafely.','常规框架：判断力差的人追求危险与无用的快感。重构框架：人活着需要最低限度的快感，得不到就会冒险去争取。',95,true),
('mental-49','Mental Health Reframes','意志力','Usual Frame: Some people have no willpower. They are weak. Reframe: Some people get more pleasure from certain vices than you do.','常规框架：有些人没有意志力很软弱。重构框架：有些人从某些恶习中获得的快感比你多。',96,true),
('mental-50','Mental Health Reframes','好坏日子','Usual Frame: There are good days and bad. Reframe: All days are useful in different ways.','常规框架：有好日子和坏日子。重构框架：每一天都各有用处。',97,true),
('mental-51','Mental Health Reframes','自由','Usual Frame: Freedom is the ability to do what you want. Reframe: Freedom''s just another word for nothing left to lose.','常规框架：自由就是做想做的事。重构框架：自由的本质是无所失去。',98,true),
('mental-52','Mental Health Reframes','面向未来','Usual Frame: I can''t handle this for the rest of my life. Reframe: I can do anything for a day.','常规框架：我无法忍受一辈子这样。重构框架：一天什么都能撑过去。',99,true),
('mental-53','Mental Health Reframes','创伤与历史','Usual Frame: I am a victim of my past traumas. Reframe: History is imaginary.','常规框架：我是过往创伤的受害者。重构框架：历史是想象的。',100,true),
('mental-54','Mental Health Reframes','愤怒的来源','Usual Frame: I am angry because something happened. Reframe: I am living in the past.','常规框架：某事让我愤怒。重构框架：我活在过去。',101,true),
('mental-55','Mental Health Reframes','焦虑本质','Usual Frame: I am anxious. Reframe: I am living in the future (but not in a good way).','常规框架：我很焦虑。重构框架：我活在对未来的忧虑中。',102,true),
('mental-56','Mental Health Reframes','创伤定义','Usual Frame: You are the result of your traumas. Reframe: You are a random bundle of loose wires.','常规框架：你是你创伤的产物。重构框架：你只是乱糟糟的神经集合。',103,true),
('mental-57','Mental Health Reframes','创伤与力量','Usual Frame: My trauma crippled me. Reframe: My trauma is why I can kick your ass.','常规框架：创伤让我残缺。重构框架：创伤让我更强大。',104,true),
('mental-58','Mental Health Reframes','活在当下','Usual Frame: Live in the now. Reframe: Imagine even your smallest actions influencing your future.','常规框架：活在当下。重构框架：想象每个小动作都影响未来。',105,true),
('mental-59','Mental Health Reframes','安全感','Usual Frame: Safe things are safe. Dangerous things are dangerous. Reframe: Safe-looking things can be dangerous. Dangerous-looking things can be safe.','常规框架：安全的就是安全的，危险的就是危险的。重构框架：看似安全的可能危险，看似危险的可能安全。',106,true),
('mental-60','Mental Health Reframes','幸福来源','Usual Frame: Happiness comes from within. Reframe: Use the external world to program your brain for happiness.','常规框架：幸福来自内心。重构框架：用外界来训练你的幸福。',107,true),
('mental-61','Mental Health Reframes','心理结构','Usual Frame: My mind is in my brain. Reframe: My mind includes my brain, body, and physical environment. Any change to one changes the others.','常规框架：我的思想只在大脑里。重构框架：我的思想包含大脑、身体和物理环境，任何一处变化都会影响整体。',108,true),
('social-1','Social Life Reframes','做自己','Usual Frame: Be yourself. Reframe: Become a better version of yourself.','常规框架：做你自己。重构框架：成为更好的自己。',109,true),
('social-2','Social Life Reframes','爱自己','Usual Frame: Learn to love yourself as you are. Reframe: Be glad your brain is pestering you to improve.','常规框架：学会爱本来的自己。重构框架：庆幸你的大脑催促你进步。',110,true),
('social-3','Social Life Reframes','建议他人','Usual Frame: This person needs my advice. Reframe: This person might need some information, empathy, or some help organizing their thoughts.','常规框架：这个人需要我的建议。重构框架：对方可能只需要信息、共情或帮他理清思路。',111,true),
('social-4','Social Life Reframes','抱怨','Usual Frame: People who complain want solutions. Reframe: Some people who complain just enjoy complaining.','常规框架：抱怨的人想要解决方案。重构框架：有些人只是喜欢抱怨。',112,true),
('social-5','Social Life Reframes','强势性格','Usual Frame: This person has a strong personality. I must become stronger to deal with it as an equal. Reframe: This person is toxic. I must escape now.','常规框架：这个人性格很强势，我要变得更强以平等相待。重构框架：这个人有毒，我要马上远离。',113,true),
('social-6','Social Life Reframes','赞美','Usual Frame: Giving compliments is awkward, creepy, or manipulative. Reframe: Withholding a compliment is almost immoral.','常规框架：夸奖别人很尴尬、做作或有目的。重构框架：吝啬赞美几乎是不道德的。',114,true),
('social-7','Social Life Reframes','吸引力','Usual Frame: No one seems to find me attractive. Reframe: I haven''t met enough people.','常规框架：没人觉得我有魅力。重构框架：我还没遇到足够多人。',115,true),
('social-8','Social Life Reframes','寻找伴侣','Usual Frame: I need to go find someone to be my romantic partner. Reframe: I need to signal my genetic advantages to attract a romantic partner.','常规框架：我要主动找对象。重构框架：我要展示自身基因优势来吸引对象。',116,true),
('social-9','Social Life Reframes','饭局纠结','Usual Frame: I''m trying to make a dining decision with a crazy person. Please shoot me. Reframe: It''s not about food. It''s about the illusion of control.','常规框架：与一个"疯子"讨论吃什么太痛苦了。重构框架：这不是食物问题，而是控制感问题。',117,true),
('social-10','Social Life Reframes','决策分担','Usual Frame: I need a decision. Reframe: I need a copilot to share the blame.','常规框架：我需要一个决定。重构框架：我需要一个搭档来分担责任。',118,true),
('social-11','Social Life Reframes','幽默的本质','Usual Frame: The usual patterns hold (non-humor). Reframe: The usual patterns are violated (humor).','常规框架：一切按常理出牌（通常不幽默）。重构框架：打破常规才有幽默。',119,true),
('social-12','Social Life Reframes','婚姻观念1','Usual Frame: Marriage is about finding your soul mate. Reframe: Marriage is about finding love with someone who values promises.','常规框架：婚姻就是找到灵魂伴侣。重构框架：婚姻是和重视承诺的人相爱。',120,true),
('social-13','Social Life Reframes','婚姻观念2','Usual Frame: Marriage is a great system, so if your marriage fails, that means one or both of you messed up. Reframe: So many marriages ending in divorce proves that marriage is a poorly designed system.','常规框架：婚姻制度很棒，失败是个人原因。重构框架：离婚比例高说明婚姻制度设计有问题。',121,true),
('social-14','Social Life Reframes','永恒关系','Usual Frame: I want my relationship to last forever. Reframe: Nothing lasts forever.','常规框架：我希望关系天长地久。重构框架：没有什么能永恒。',122,true),
('social-15','Social Life Reframes','失恋','Usual Frame: This breakup ends my hopes for happiness. Reframe: There are happier third marriages than first.','常规框架：失恋让我不再有幸福希望。重构框架：第三次婚姻也许比第一次更幸福。',123,true),
('social-16','Social Life Reframes','灵魂伴侣丧失','Usual Frame: I have lost my soulmate. Reframe: I have a million soulmates I have not yet met.','常规框架：我失去了我的灵魂伴侣。重构框架：还有无数灵魂伴侣等我遇见。',124,true),
('social-17','Social Life Reframes','失恋难过','Usual Frame: I am crying because my relationship ended. Reframe: ''Don''t cry because it is over, smile because it happened.''- Dr. Seuss','常规框架：分手让我痛哭。重构框架："不要因结束而哭泣，要为曾拥有而微笑。"- - 苏斯博士',125,true),
('social-18','Social Life Reframes','父母与青少年','Usual Frame: A teen can''t understand the "reason" parents have given, and it turns into a power struggle. Reframe: The parent is a guide for young brains that are not yet capable of understanding adult reasons.','常规框架：青少年不理解父母的理由，变成权力斗争。重构框架：父母是指引未成熟大脑的向导。',126,true),
('social-19','Social Life Reframes','孩子教育','Usual Frame: I''m talking to you, teen, and this is between us. Reframe: I must answer to your future self, not your current self.','常规框架：我和你（青少年）谈话只是现在的你和我。重构框架：我要对你未来的自己负责。',127,true),
('social-20','Social Life Reframes','他人影响','Usual Frame: People treat you poorly, and you can''t do much about it. Reframe: You cause people to act the way they do.','常规框架：别人对你不好，你无能为力。重构框架：别人的行为受你影响。',128,true),
('social-21','Social Life Reframes','谁主沉浮','Usual Frame: The boss is in charge. Reframe: The person with the best ideas is in charge.','常规框架：老板说了算。重构框架：最有主意的人说了算。',129,true),
('social-22','Social Life Reframes','权威','Usual Frame: The experts are in charge. Reframe: The best communicator is in charge.','常规框架：专家说了算。重构框架：表达能力强的说了算。',130,true),
('social-23','Social Life Reframes','能力与权力','Usual Frame: The boss is in charge. Reframe: The most capable people are in charge.','常规框架：老板在位。重构框架：最能干的人真正主导。',131,true),
('social-24','Social Life Reframes','权力本质','Usual Frame: The people in charge have the power. Reframe: Power = (Persuasion skill) x (Audience size)','常规框架：领导就有权力。重构框架：权力=说服力×受众规模。',132,true),
('social-25','Social Life Reframes','动机猜测','Usual Frame: I can discern people''s motives by their actions. Reframe: Mind-reading isn''t real. Humans are terrible at discerning motives.','常规框架：我能从行为判断动机。重构框架：读心术并不存在，人并不擅长看穿动机。',133,true),
('social-26','Social Life Reframes','正常与疯子','Usual Frame: Most people are normal, but I''m a basket case. Reframe: Everyone is a basket case once you get to know them.','常规框架：大多数人正常，只有我是另类。重构框架：每个人其实都是"神经兮兮"，只要你深入了解。',134,true),
('social-27','Social Life Reframes','错误的评判','Usual Frame: Judge people by their mistakes. Reframe: Judge people by how they respond to their mistakes.','常规框架：以错误评判他人。重构框架：看别人如何面对错误来评判。',135,true),
('social-28','Social Life Reframes','时间观念','Usual Frame: People who are always late are either incompetent or uncaring or both. Reframe: Some people have time blindness.','常规框架：总迟到的人要么无能要么不在乎。重构框架：有些人有"时间失明"。',136,true),
('social-29','Social Life Reframes','小善举','Usual Frame: Small acts of kindness are good. Reframe: There are no small acts of kindness.','常规框架：小小善举也是好事。重构框架：善意没有大小之分。',137,true),
('physical-1','Physical Health Reframes','饥饿与进食','Usual Frame: When I am hungry, I eat food. Reframe: Some food is fuel. Some food is entertainment.','常规框架：饿了就吃东西。重构框架：有的食物是能量，有的只是娱乐。',138,true),
('physical-2','Physical Health Reframes','暴饮暴食','Usual Frame: Overeating is a willpower problem. Reframe: Overeating is a knowledge problem.','常规框架：吃太多是意志力差。重构框架：吃太多是知识不足。',139,true),
('physical-3','Physical Health Reframes','选择食物','Usual Frame: I eat too much of the wrong food. Reframe: I spend too much time with the wrong people.','常规框架：我总是吃错东西。重构框架：我总是跟错人待在一起。',140,true),
('physical-4','Physical Health Reframes','渴望食物','Usual Frame: I want food, so I must be hungry. Reframe: I want food, so I might be tired.','常规框架：想吃东西就说明我饿了。重构框架：想吃东西也许只是我累了。',141,true),
('physical-5','Physical Health Reframes','减肥目标','Usual Frame: I have a weight loss goal. Reframe: I need to create a weight loss system for myself.','常规框架：我有个减肥目标。重构框架：我需要为自己建立减肥系统。',142,true),
('physical-6','Physical Health Reframes','糖分','Usual Frame: Sugar is delicious but don''t overdo it. Reframe: Sugar is poison.','常规框架：糖很美味，只要不过量就好。重构框架：糖是毒药。',143,true),
('physical-7','Physical Health Reframes','碳水诱惑','Usual Frame: I am tempted by bad carbs. Reframe: I''m not the kind of person who eats bad carbs.','常规框架：我容易被不健康碳水吸引。重构框架：我不是爱吃不健康碳水的人。',144,true),
('physical-8','Physical Health Reframes','吃撑','Usual Frame: My stomach has room for more food. Reframe: I''ve had enough.','常规框架：我胃里还能再装点。重构框架：我已经足够了。',145,true),
('physical-9','Physical Health Reframes','饥饿感','Usual Frame: I''m hungry, so I need food. Reframe: I''m hungry, so I need protein.','常规框架：我饿了，需要吃东西。重构框架：我饿了，要吃蛋白质。',146,true),
('physical-10','Physical Health Reframes','锻炼习惯','Usual Frame: Exercising requires willpower and motivation. Reframe: Exercising is easier than not exercising if you turn it into a habit.','常规框架：锻炼需要意志力和动力。重构框架：一旦习惯成自然，锻炼比不锻炼更容易。',147,true),
('physical-11','Physical Health Reframes','健身方式','Usual Frame: It''s important to learn the best ways to exercise. Reframe: The best exercises are the ones you are willing to do.','常规框架：找到最科学的锻炼方式很重要。重构框架：最好的锻炼方式是你愿意坚持的那种。',148,true),
('physical-12','Physical Health Reframes','睡眠和努力','Usual Frame: I can''t get to sleep. Reframe: I didn''t work hard enough.','常规框架：我失眠了。重构框架：我还不够努力。',149,true),
('reality-1','Reality Reframes','核能','Usual Frame: Nuclear Power is risky. Reframe: Nuclear power is green.','常规框架：核能很危险。重构框架：核能是绿色能源。',150,true),
('reality-2','Reality Reframes','人类理性','Usual Frame: People are rational 90 percent of the time. Reframe: People are rational 10 percent of the time if that.','常规框架：人类90%的时候是理性的。重构框架：人类就算有10%时间理性就不错了。',151,true),
('reality-3','Reality Reframes','对错观','Usual Frame: One of us is right, and one is wrong. Reframe: We are watching two different movies on one screen.','常规框架：我们之间必有对错。重构框架：我们像在一块屏幕前看不同的电影。',152,true),
('reality-4','Reality Reframes','遗传观','Usual Frame: You should spread your genes. Reframe: No matter what you do, your genes will be diluted with each generation until your contribution nears zero.','常规框架：你应该传播基因。重构框架：无论你怎么做，你的基因每一代都会被稀释，直至趋于零。',153,true),
('reality-5','Reality Reframes','世界观','Usual Frame: The best worldview is the true one. Reframe: The best worldview is one that predicts the best.','常规框架：最好的世界观是真实的世界观。重构框架：最好的世界观是能带来最好结果的。',154,true),
('reality-6','Reality Reframes','行为预测','Usual Frame: Predicting people''s actions involves many variables. Reframe: Follow the money. That''s all you need.','常规框架：预测行为需要很多变量。重构框架：只要看钱往哪流就够了。',155,true),
('reality-7','Reality Reframes','人生意义','Usual Frame: Life is about avoiding pain while pursuing happiness and meaning. Reframe: Life is an adventure.','常规框架：人生就是避免痛苦、追求幸福与意义。重构框架：人生是一场冒险。',156,true),
('reality-8','Reality Reframes','推定无罪','Usual Frame: Everyone is innocent until proven guilty. Reframe: Citizens are innocent until proven guilty. Corporations and governments are presumed guilty until proven innocent.','常规框架：所有人未经证实就是清白的。重构框架：个人如此，公司和政府默认有罪，需自证清白。',157,true),
('reality-9','Reality Reframes','作弊观','Usual Frame: No cheating has been detected, so the organization is innocent. Reframe: Whenever there is an opportunity for cheating and not getting caught, a lot to gain from cheating, and lots of people involved, cheating will always happen.','常规框架：没有发现作弊就代表组织清白。重构框架：有利可图且不易被发现、参与者多的地方作弊肯定存在。',158,true),
('reality-10','Reality Reframes','舆论与观点','Usual Frame: People come up with their own opinions. Reframe: People join teams, and the media assigns their opinions.','常规框架：人们自行形成观点。重构框架：人们加入阵营，媒体替他们分配观点。',159,true),
('reality-11','Reality Reframes','人性差异','Usual Frame: Others think and feel approximately as I do. Reframe: Others are unimaginably different.','常规框架：别人和我想法差不多。重构框架：别人和你极不相同。',160,true),
('os-1','The Operating System for Your Mind','自我塑造','Usual Frame: You are the product of your experiences and genes. Reframe: You are the author of your experience.','常规框架：你是你的经历和基因的产物。重构框架：你是自己经历的创作者。',161,true),
('os-2','The Operating System for Your Mind','对待他人','Usual Frame: I deserve to be treated well by others. Reframe: You get what you give, on average. No one deserves anything.','常规框架：我理应被他人善待。重构框架：你付出什么大致会收获什么。没有人天生值得被优待。',162,true),
('os-3','The Operating System for Your Mind','现实本质','Usual Frame: Reality is objective, and science helps us understand it. Reframe: Our so-called reality is a simulation created by a higher intelligence.','常规框架：现实是客观的，科学可以解释现实。重构框架：我们的现实其实是由更高智慧创造的模拟。',163,true),
('os-4','The Operating System for Your Mind','人生如游戏','Alternate: You are in a video game, and you have certain problems to solve to get to the next level.','补充：你就像在一款电子游戏里，必须解决某些问题才能进入新关卡。',164,true),
('os-5','The Operating System for Your Mind','记忆的不同','Usual Frame: We have different memories. Reframe: We created different subjective realities.','常规框架：我们有不同的记忆。重构框架：我们创造了不同的主观现实。',165,true),
('os-6','The Operating System for Your Mind','现实主观性','Usual Frame: Reality is objective. Reframe: There might be an objective reality, but human brains don''t have access to it.','常规框架：现实是客观的。重构框架：客观现实可能存在，但人脑接触不到。',166,true),
('os-7','The Operating System for Your Mind','一切皆主观','Usual Frame: Reality is only subjective in terms of our opinions and preferences. Reframe: We can treat all of reality as subjective and get a good outcome, as if we authored it ourselves.','常规框架：现实只有在观点和偏好上才是主观的。重构框架：我们可以把整个现实都当作主观的，反而能获得更好的结果，就像我们亲手创造的一样。',167,true);
